config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  } 
  resources :user_details do
    collection do
      get :verify_age
    end
  end
  resources :home
  root 'home#index'
  # get "*path" => redirect("/")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
	belongs_to :user
	has_one_attached :medical_status
	has_one_attached :proof_type_front
	has_one_attached :proof_type_back
	has_one_attached :profile
	# phony_normalize :contact_number, default_country_code: 'US'
	enum medical_status_result: [:Negative, :Confidentaial, :I_will_tell_later]
	before_create :verify_age
	validates :birthday, presence: true
	validates :user_name, presence: true
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
	def index
		@userdetail = UserDetail.find_or_initialize_by(user_id: current_user.id)
	end
	def show
    @userdetail = current_user.user_detail
	end
	def new
		@userdetail = current_user.build_user_detail
	end
	def edit
	  @userdetails = current_user.user_detail
	end
	def create
	  @userdetails = UserDetail.new(userdetails)
	  @userdetails.user = current_user
    respond_to do |format|
      if @userdetails.save
      	@age = ((Time.zone.now - @userdetails.birthday.to_time) / 1.year.seconds).floor
      	if @age < 21
					format.html { render :verify_age }
					flash[:failure] = "Oops you're not 21 years old or older. Try again or sign up."
				else	
	        format.html { redirect_to user_details_path, notice: 'Userdetails were successfully created.' }
	        format.json { render :show, status: :created, location: @userdetails }
	        format.js
	    	end    
      else
        format.html { render :new }
        format.json { render json: @userdetails.errors, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

	def update
    @userdetail = current_user.user_detail
    respond_to do |format|
	    if @userdetail.update(userdetails)
    		@age = ((Time.zone.now - @userdetail.birthday.to_time) / 1.year.seconds).floor
    		if @age < 21
					format.html { render :verify_age }
					flash[:failure] = "Oops you're not 21 years old or older. Try again or sign up."
				else
		      format.html { redirect_to user_details_path, notice: 'Userdetails were successfully updated.' }
		      format.json { render :show, status: :ok, location: @userdetails }
	      end
	    else
	      format.html { render :edit }
	      format.json { render json: @userdetails.errors, status: :unprocessable_entity }
	    end
  	end
  end

	private
		def userdetails
      params.require(:user_detail).permit(:user_name, :birthday, :contact_number, :city, :state, :country, :medical_status_date_checked, :medical_status_result, :medical_status, :proof_type, :proof_type_front, :proof_type_back, :profile, :verify_age)
		end
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/user_details/_identification_details.html.erb
<h4 class="sub_ttl">To protect minors and prevents fake ads, please upload a government issued identification.</h4>
<div class="identity_radio">
  <div class="row">
    <div class="col-lg-4 col-sm-4">
      <%= f.radio_button :proof_type, 'driving_licence' %>
      <%= f.label :Driving_License%>
    </div>
    <div class="col-lg-4 col-sm-4">
      <%= f.radio_button :proof_type, 'passport' %>
      <%= f.label :Passport%>
    </div>
    <div class="col-lg-4 col-sm-4">
      <%= f.radio_button :proof_type, 'state_id' %>
      <%= f.label :State_ID%>
    </div>
  </div>
</div>
<div class="identi_block">
  <h4 class="sub_ttl">Upload Front Side</h4>
  <div class="row">
    <div class="col-lg-12">
      <!-- <div class="custom_fileupload"> -->
        <%= f.file_field :proof_type_front %>
        <%= f.label :Front_side %>
      <!-- </div> -->
    </div>
  </div>
</div>
<div class="identi_block">
  <h4 class="sub_ttl">Upload ID again while you hold it	</h4>
  <div class="row">
    <div class="col-lg-12">
      <!-- <div class="custom_fileupload"> -->
        <%= f.file_field :proof_type_back %>
        <%= f.label :Back_side %>
      <!-- </div> -->
    </div>
  </div>
</div>
<div class="info">
  <p>This data is used only for age and identity's verification.</p>
</div>
<div class="save_cancel_btn">
  <div class="row">
    <div class="col-lg-6 col">
      <!-- <button class="button" type="submit">Cancel</button> -->
    </div>
    <div class="col-lg-6 col">
      <%= f.submit "Submit", class: "button" %>
    </div>
  </div>
</div>

app/views/user_details/_medical_details.html.erb
<div class="custom_dropdown">
  <h4 class="sub_ttl">When was the last time you check your status?</h4>
  <div class="row">
    <div class="col-lg-12 col-sm-12">
      <div class="dropdown_box">
        <%= f.date_select :medical_status_date_checked, prompt: { day: t('.day'), month: t('.month'), year: t('.year') }, start_year: Date.today.year, end_year: Date.today.year - 100, order: [:month, :day, :year]%>
      </div>
    </div>
  </div>      
</div>
<div class="custom_dropdown medical_block">
  <h4 class="sub_ttl">If so, whaat was the result?</h4>
  <div class="row">
    <div class="col-lg-12">
      <div class="dropdown_box">
        <%= f.select :medical_status_result, options_for_select(UserDetail.medical_status_results.keys.map { |w| [w.humanize, w]}, @userdetail.medical_status_result), class: "results_order" %>
      </div>
    </div>
  </div>      
</div>
<div class="custom_dropdown medical_block">
  <h4 class="sub_ttl">Upload result</h4>
    <%= f.file_field :medical_status, placeholder: "Upload result here" %>
</div>
<div class="info">
  <p>Ad with status is listed under "Sin City Zone" and makes people feel safe.</p>
</div>
<div class="save_cancel_btn">
  <div class="row">
    <div class="col-lg-6 col">
      <!-- <button class="button" type="submit">Cancel</button> -->
    </div>
    <div class="col-lg-6 col">
      <%= f.submit "Submit", class: "button" %>
    </div>
  </div>
</div>

app/views/user_details/_personal_details.html.erb
<div class="user_name"> <i class="fa fa-user"></i>
	<%= f.text_field :user_name, class: "form-control", placeholder: "Username" %>
  <%= print_error(@userdetail.errors, :user_name) %>
</div>

<div class="custom_dropdown">
  <div class="row">
    <div class="col-lg-12 col-sm-12">
      <div class="dropdown_box">
	     <%= f.date_select :birthday, prompt: { day: t('.day'), month: t('.month'), year: t('.year') }, start_year: Date.today.year, end_year: Date.today.year - 100, order: [:month, :day, :year]%>
       <%= print_error(@userdetail.errors, :birthday) %>
      </div>
    </div>
  </div>
</div>

<div class="user_call"> <i class="fa fa-phone"></i>
	<%= f.text_field :contact_number, class: "form-control" %>
</div>

<!-- <div class="field"> -->
  <!-- <div class="country_code_wrapper">
    <div class="country_code_body">
      <span class="country_code_customer full_info_country_code_customer none">+<%#= @country_code %></span>
    </div> -->

    <!-- <div class="country_code_form"> -->
      <!-- <input type="tel" value="<%#= params[:user_detail] %>" id="onlyphoneyVal"> -->
      <%#= f.hidden_field :contact_number, value: params[:user_detail][:contact_number], class: 'universal_bookings_form_for_phone', id: 'only_contact_number' %>
      <%#= f.hidden_field :preferred_contact, value: 'emailsms' %>
      <%#= f.hidden_field_tag :flag, true %>
    <!-- </div> -->
  <!-- </div> -->
<!-- </div> -->

<div class="user_msg"> <i class="fa fa-envelope"></i>
	<div class="form-control">
		<%= current_user.email%>
	</div>
</div>

<%#= f.intl_tel_input(:contact_number) %>

<div class="custom_dropdown">
	<div class="row">
  	<div class="col-lg-6 col-sm-6">
      <div class="dropdown_box">
      	<%= f.label :city %>
				<%= f.text_field :city %>
      	<%= f.label :state %>
				<%= f.text_field :state %>
      </div>
  	</div>
	</div>
</div>

<div class="save_cancel_btn">
  <div class="row">
    <div class="col-lg-6 col">
      <!-- <button class="button" type="submit">Cancel</button> -->
    </div>
    <div class="col-lg-6 col">
      <%= f.submit "Submit", class: "button" %>
    </div>
  </div>
</div>


<script type="text/javascript">
  var country_code = $('.country_code_customer').text()
console.log(country_code)
var telponly = $("#onlyphoneyVal")
telponly.intlTelInput({
initialCountry: "auto",
preferredCountries: [''],
separateDialCode: true,
  geoIpLookup: function(callback) {
    $.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
      var countryCode = (resp && resp.country) ? resp.country : "";
      callback(countryCode);
    });
  },
  utilsScript: "assets/libphonenumber/utils.js"
});

telponly.each(function () {
  $(this).keyup(function () {
    if(Math.floor($(this).val()) == $(this).val() || $.isNumeric($(this).val())) {
      $('.country_code_customer').addClass('none')
      telponly.intlTelInput({
      initialCountry: "auto",
      preferredCountries: [''],
      separateDialCode: true,
        geoIpLookup: function(callback) {
          $.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
            var countryCode = (resp && resp.country) ? resp.country : "";
            callback(countryCode);
          });
        },
        utilsScript: "assets/libphonenumber/utils.js"
      })
      var intlNumber = $(this).intlTelInput("getNumber")
      $('#post_preferred_contact').val('emailsms')
      $('.universal_bookings_form_for_phone').attr('id','only_contact_number')
      $('.universal_bookings_form_for_phone').attr('name','contact_number')
      $('#only_contact_number').val(intlNumber)

    } else {
      telponly.intlTelInput("destroy");
      $('#onlyphoneyVal').focus();
      $(this).next('input').val($(this).val())
      $('.country_code_customer').removeClass('none')
      $('.country_code_customer').text('@')
      // // $('#emailForLabel').fadeIn()
      $('#post_preferred_contact').val('email')
      $('.universal_bookings_form_for_phone').attr('id','email')
      $('.universal_bookings_form_for_phone').attr('name','email')
    }
  })
})
</script>

app/views/user_details/edit.html.erb
<h1>Edit User Details</h1>

app/views/user_details/extra.html.erb
<div class="user_info gray_bg">
  <div class="container">
    <div class="white_bg">
      <div class="row">
        <div class="col-lg-3 col-sm-4">
          <div class="user_details">
            <div class="user_image">
              <%= link_to root_path do %>
                <%= image_tag "default.jpg" %>
              <% end %>
            </div>
            <div class="user_menu">
              <ul>
                <li><a href="#"><i class="fa fa-user"></i>Personal</a></li>
                <li><a href="#"><i class="fa fa-edit"></i>My ad</a></li>
                <li><a href="#"><i class="fa fa-medkit"></i>My health</a></li>
                <li><a href="#"><i class="fa fa-id-card"></i>Identification</a></li>
                <li><a href="#"><i class="fa fa-bell-o"></i>Notification</a></li>
                <li><a href="#"><i class="fa fa-cog"></i>Security</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-9 col-sm-8">
          <div class="user_form">
            <section id="tabs">
              <nav>
                <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist"> <a class="nav-item nav-link active" id="nav-personal-tab" data-toggle="tab" href="#nav-personal" role="tab" aria-controls="nav-personal" aria-selected="true">Personal</a> <a class="nav-item nav-link" id="nav-medical-tab" data-toggle="tab" href="#nav-medical" role="tab" aria-controls="nav-medical" aria-selected="false">Medical</a> <a class="nav-item nav-link" id="nav-identification-tab" data-toggle="tab" href="#nav-identification" role="tab" aria-controls="nav-identification" aria-selected="false">Identification</a> </div>
              </nav>
              <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-personal" role="tabpanel" aria-labelledby="nav-personal-tab">
                  <div class="user_data">
                  	<%= form_for @userdetails, :url => { :action => "create" }, remote: true do |f| %>
						          <div class="user_name"> <i class="fa fa-user"></i>
							         <%= f.text_field :user_name, class: "form-control", placeholder: "Username" %>
                      </div>
                      <div class="custom_dropdown">
                        <div class="row">
                          <div class="col-lg-4 col-sm-4">
                            <div class="dropdown_box">
  							              <%= f.date_select :birthday, prompt: { day: t('.day'), month: t('.month'), year: t('.year') }, start_year: Date.today.year, end_year: Date.today.year - 100, order: [:month, :day, :year]%>
                            </div>
                          </div>    
  						          </div>
  					          </div>
                      <div class="user_call"> <i class="fa fa-phone"></i>
                        <input type="text" class="form-control" placeholder="(781) 123 13-4561">
                      </div>
                      <div class="user_msg"> <i class="fa fa-envelope"></i>
                        <input type="email" class="form-control" placeholder="Email Address">
                      </div>
                      <div class="custom_dropdown">
                        <div class="row">
                          <div class="col-lg-6 col-sm-6">
                            <div class="dropdown_box">
              					      <%= f.label :country %>
                              <%= f.select :country, CS.countries%>
                              <%= f.label :state %>
                              <%= f.select :state, CS.states(:IN)%>
                              <%= f.label :city %>
                              <%= f.select :city, CS.cities(:AP, :IN)%></br>
                            </div>
                          </div>
                        </div>
                      </div>        
						          <%= f.submit "Submit", class: "button" %>
					          <% end %>
                  </div>
                </div>
                <div class="tab-pane fade" id="nav-medical" role="tabpanel" aria-labelledby="nav-medical-tab">
                  <div class="user_data">
                    <%= form_for @user_details, :url => { :action => "create" }, remote: true do |f| %>
                      <div class="custom_dropdown">
                        <h4 class="sub_ttl">When was the last time you check your status?</h4>
                        <div class="row">
                          <%= f.date_select :birthday, prompt: { day: t('.day'), month: t('.month'), year: t('.year') }, start_year: Date.today.year, end_year: Date.today.year - 100, order: [:month, :day, :year]%>
                        </div>
                      </div>
                      <div class="custom_dropdown medical_block">
                        <h4 class="sub_ttl">If so, whaat was the result?</h4>
                        <div class="row">
                          <%= f.select :medical_status_result, options_for_select(User.medical_status_results.keys.map { |w| [w.humanize, w]}, @user_details.medical_status_result), class: "results_order" %>
                        </div>
                      </div>
                      <div class="custom_dropdown medical_block">
                        <h4 class="sub_ttl">Upload result</h4>
                        <div class="row">
                          <%= f.file_field :medical_status %>
                        </div>
                      </div>
                      <div class="info">
                        <p>Ad with status is listed under "Sin City Zone" and makes people feel safe.</p>
                      </div>
                      <div class="save_cancel_btn">
                        <div class="row">
                          <div class="col-lg-6 col">
                            <button class="button" type="submit">Cancel</button>
                          </div>
                          <div class="col-lg-6 col">
                            <%= f.submit "Submit", class: "button" %>
                            <!-- <button class="button" type="submit">Save</button> -->
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
                <div class="tab-pane fade" id="nav-identification" role="tabpanel" aria-labelledby="nav-identification-tab">
                  <div class="user_data user_identification">
                    <%= form_for @user_details, :url => { :action => "create" }, remote: true do |f| %>
                      <h4 class="sub_ttl">To protect minors and prevents fake ads, please upload a government issued identification.</h4>
                      <div class="identity_radio">
                        <div class="row">
                          <div class="col-lg-4 col-sm-4">
                            <%= f.radio_button :proof_type, 'driving_licence' %>
                            <%= f.label :Driving_License%>
                          </div>
                          <div class="col-lg-4 col-sm-4">
                            <%= f.radio_button :proof_type, 'passport' %>
                            <%= f.label :Passport%>
                          </div>
                          <div class="col-lg-4 col-sm-4">
                            <%= f.radio_button :proof_type, 'state_id' %>
                            <%= f.label :State_ID%>
                          </div>
                        </div>
                      </div>
                      <div class="identi_block">
                        <h4 class="sub_ttl">Upload Front Side</h4>
                        <div class="row">
                          <div class="col-lg-12">
                            <!-- <div class="custom_fileupload"> -->
                              <%= f.file_field :proof_type_front %>
                              <%= f.label :Front_side %>
                            <!-- </div> -->
                          </div>
                        </div>
                      </div>
                      <div class="identi_block">
                        <h4 class="sub_ttl">Upload ID again while you hold it	</h4>
                        <div class="row">
                          <div class="col-lg-12">
                            <!-- <div class="custom_fileupload"> -->
                              <%= f.file_field :proof_type_back %>
                              <%= f.label :Back_side %>
                            <!-- </div> -->
                          </div>
                        </div>
                      </div>
                      <div class="info">
                        <p>This data is used only for age and identity's verification.</p>
                      </div>
                      <div class="save_cancel_btn">
                        <div class="row">
                          <div class="col-lg-6 col">
                            <button class="button" type="submit">Cancel</button>
                          </div>
                          <div class="col-lg-6 col">
                            <%= f.submit "Submit", class: "button" %>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  // $( "#user_country" ).click(function() {
  //   var country = $("#user_country").val();
  //   var state = $("#user_state").value = country;
  //   console.log(country);
  //   console.log("1111111111111111111")
  //   console.log(state)
  // });
  $('#user_country').change(function () {
    var country = $(this).val();
    console.log(country)
    if (country) {
     var state = $('#user_state').val(country);
     console.log(state)
    }
  });
</script>

app/views/user_details/index.html.erb
<div class="user_info gray_bg">
  <div class="container">
    <div class="white_bg">
      <div class="row">
        <div class="col-lg-3 col-sm-4">
          <div class="user_details">
            <div class="user_image">
              <%= form_for @userdetail do |f| %>
                <%= f.file_field :profile, onchange: 'this.form.submit()' %>
                <%if @userdetail.profile.attached? %>
                  <%= image_tag @userdetail.profile.variant(resize: '150x150') %>
                <%else%>
                  <%= image_tag "default.jpg"%>
                <%end%>  
              <% end %>
            </div>
            <div class="user_menu">
              <ul>
                <li><a href="#"><i class="fa fa-user"></i>Personal</a></li>
                <li><a href="#"><i class="fa fa-edit"></i>My ad</a></li>
                <li><a href="#"><i class="fa fa-medkit"></i>My health</a></li>
                <li><a href="#"><i class="fa fa-id-card"></i>Identification</a></li>
                <li><a href="#"><i class="fa fa-bell-o"></i>Notification</a></li>
                <li><a href="#"><i class="fa fa-cog"></i>Security</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-9 col-sm-8">
          <div class="user_form">
            <section id="tabs">
              <nav>
                <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist"> <a class="nav-item nav-link active" id="nav-personal-tab" data-toggle="tab" href="#nav-personal" role="tab" aria-controls="nav-personal" aria-selected="true">Personal</a> <a class="nav-item nav-link" id="nav-medical-tab" data-toggle="tab" href="#nav-medical" role="tab" aria-controls="nav-medical" aria-selected="false">Medical</a> <a class="nav-item nav-link" id="nav-identification-tab" data-toggle="tab" href="#nav-identification" role="tab" aria-controls="nav-identification" aria-selected="false">Identification</a> </div>
              </nav>
              <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-personal" role="tabpanel" aria-labelledby="nav-personal-tab">
                	<div class="user_data">
                		<%= form_for @userdetail do |f| %>
						          <%= render 'personal_details', f: f %>
					          <% end %>
                	</div>
                </div>
                <div class="tab-pane fade" id="nav-medical" role="tabpanel" aria-labelledby="nav-medical-tab">
                  <div class="user_data">
                    <%= form_for @userdetail do |f| %>
                      <%= render 'medical_details', f: f %>
                    <% end %>
                  </div>
                </div>
                <div class="tab-pane fade" id="nav-identification" role="tabpanel" aria-labelledby="nav-identification-tab">
                  <div class="user_data user_identification">
                    <%= form_for @userdetail do |f| %>
                      <%= render 'identification_details', f: f %>
                    <% end %>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style type="text/css">
  .user_info .user_details .user_image{
    position: relative;
  }
  .user_image input{
    position: absolute;
    opacity: 0;
    height: 100%;
    cursor: pointer;
    width: 100%;
  }
</style>

app/views/user_details/new.html.erb
<h3>New user Details</h3>
<%= form_for @userdetail, url: userdetails_path do |f| %>
	<%= render 'form', f: f %>
<% end %>

app/views/user_details/show.html.erb
<h1>Show User Details</h1>
<%= form_for @userdetail, url: user_detail_path(id: @userdetail.id) do |f| %>
	<%= render 'medical_details', f: f %>
	<%= image_tag @userdetail.medical_status %>
<% end %>

app/views/user_details/verify_age.html.erb
<div class="verify_age gray_bg">
  <div class="container">
    <div class="white_bg">
      <% if flash[:failure] %>
        <div class="alert alert-info alert-dismissible"> <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a><%= flash[:failure] %></div>
      <% end %>
      <h2 class="text-center main-ttl">Please, verify your age to gain access to <br>
        Adolbit. You must be 21 years old or older.</h2>
      <div class="custom_dropdown age-verify-block">
        <div class="row">
          <div class="col-lg-12 col-sm-12">
            <div class="dropdown_box">
              <%= form_for @userdetail do |f| %>
                <%= f.date_select :birthday, prompt: { day: t('.day'), month: t('.month'), year: t('.year') }, start_year: Date.today.year, end_year: Date.today.year - 100, order: [:month, :day, :year]%>
                <%= f.hidden_field :verify_age, value: true %>
                <p>Built with <i class="fa fa-heart"></i> to protect children online</p>
                <%= f.submit "Submit", class: "button" %>
              <% end %>
            </div>
          </div>
        </div>   
      </div>
    </div>
  </div>
</div>